import type { AuditResult } from '../../functions/_lib/audit/types';
import { argumentScore, severityBreakdown, totalFindingCount } from '../../functions/_lib/audit/stats';

// ---------------------------------------------------------------------------
// Render a full audit result as clean markdown — suitable for copy, download,
// or pasting into a doc/email/Notion/Slack.
// ---------------------------------------------------------------------------

export function auditToMarkdown(audit: AuditResult, draftTitle?: string): string {
  const lines: string[] = [];
  const score     = argumentScore(audit);
  const breakdown = severityBreakdown(audit);
  const total     = totalFindingCount(audit);

  // Header
  lines.push(`# Whetstone Audit Report`);
  if (draftTitle) lines.push(`**Draft:** ${draftTitle}`);
  lines.push(`**Date:** ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  lines.push(`**Argument quality score:** ${score}/100`);
  lines.push(`**Findings:** ${total} (${breakdown.high} high, ${breakdown.medium} medium, ${breakdown.low} low)`);
  lines.push('');

  // Central claim
  lines.push(`## Central claim`);
  lines.push(audit.centralClaim);
  lines.push('');

  // Toulmin
  lines.push(`## Argument structure`);
  lines.push(`- **Claim:** ${audit.toulmin.claim}`);
  lines.push(`- **Grounds:** ${audit.toulmin.grounds}`);
  if (audit.toulmin.statedWarrant) {
    lines.push(`- **Stated warrant:** ${audit.toulmin.statedWarrant}`);
  }
  lines.push(`- **Weakest link:** ${audit.toulmin.weakestLink}`);
  lines.push('');

  // All audit findings are structural — derivable from quoted text.
  // We label "structural" once at the top rather than every line.
  const kindLabel = 'structural';

  if (audit.toulmin.unstatedWarrants.length > 0) {
    lines.push(`### Unstated warrants`);
    for (const w of audit.toulmin.unstatedWarrants) {
      lines.push(`- **${w.warrant}** (${w.severity}, ${kindLabel})`);
      lines.push(`  *${w.necessity}*`);
    }
    lines.push('');
  }

  if (audit.namedFallacies.length > 0) {
    lines.push(`## Reasoning patterns`);
    for (const f of audit.namedFallacies) {
      lines.push(`### ${f.name} (${f.severity}, ${kindLabel})`);
      lines.push(`> "${f.quote}"`);
      lines.push(f.explanation);
      lines.push('');
    }
  }

  if (audit.loadedLanguage.length > 0) {
    lines.push(`## Loaded language`);
    for (const l of audit.loadedLanguage) {
      lines.push(`- **"${l.phrase}"** — ${l.technique} (${l.severity}, ${kindLabel})`);
      lines.push(`  ${l.explanation}`);
    }
    lines.push('');
  }

  if (audit.keyTermScrutiny.length > 0) {
    lines.push(`## Key-term scrutiny`);
    for (const k of audit.keyTermScrutiny) {
      lines.push(`- **"${k.term}"** shifts meaning (${k.issue.replace(/-/g, ' ')}, ${k.severity}, ${kindLabel})`);
      lines.push(`  Use A: "${k.usage_a}"`);
      lines.push(`  Use B: "${k.usage_b}"`);
      lines.push(`  ${k.explanation}`);
    }
    lines.push('');
  }

  if (audit.referentChecks.length > 0) {
    lines.push(`## Referent checks`);
    for (const r of audit.referentChecks) {
      lines.push(`- **"${r.phrase}"** — ${r.issue.replace(/-/g, ' ')} (${r.severity}, ${kindLabel})`);
      lines.push(`  ${r.explanation}`);
    }
    lines.push('');
  }

  if (audit.falsifiabilityChecks.length > 0) {
    lines.push(`## Falsifiability checks`);
    for (const f of audit.falsifiabilityChecks) {
      lines.push(`- **${f.claim}** — ${f.issue.replace(/-/g, ' ')} (${f.severity}, ${kindLabel})`);
      lines.push(`  ${f.explanation}`);
    }
    lines.push('');
  }

  if (audit.modalScopeChecks.length > 0) {
    lines.push(`## Modal scope checks`);
    for (const m of audit.modalScopeChecks) {
      lines.push(`- **${m.claim}** (${m.severity}, ${kindLabel})`);
      lines.push(`  "${m.inflatedModal}" → "${m.impliedModal}"`);
      lines.push(`  ${m.explanation}`);
    }
    lines.push('');
  }

  // Notes
  if (audit.notes) {
    lines.push(`## Notes`);
    lines.push(audit.notes);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [The Whetstone](https://thewhetstone.review)*');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Download as .md file
// ---------------------------------------------------------------------------

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
